import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import Footer from "@/components/common/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pro-Travels",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <div className="my-20">{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
