import { Inter } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/common/ThemeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pro-Travels-Sign in",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div>{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
